services:
  backend:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
