version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "11435:11434"
    volumes:
      - /usr/share/ollama:/root/.ollama 

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
